// Nhận bài đăng từ công cụ bên ngoài (A-AI-3dvietpro desktop tool — mục "AI
// tự động đăng bài" / hàng chờ "Đăng bài tự động") và lưu thành 1 bài blog
// thật trên chính site này, để trang /blog tự động hiện bài mới — không cần
// sửa gì thêm ở phía web, vì trang blog đã đọc thẳng từ bảng BlogPost.
//
// Xác thực bằng 1 Bearer token tĩnh (AUTOPOST_API_TOKEN, đặt trong biến môi
// trường ở cPanel) — đơn giản, đủ dùng cho 1 client duy nhất (tool của thầy),
// không cần OAuth/session vì đây là gọi máy-tới-máy, không có trình duyệt.
const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const BlogPost = require('../models/BlogPost');

const uploadDir = path.join(__dirname, '..', 'public', 'uploads');

function checkToken(req, res, next) {
  const token = process.env.AUTOPOST_API_TOKEN;
  if (!token) {
    return res.status(503).json({ error: 'Server chưa cấu hình AUTOPOST_API_TOKEN.' });
  }
  const header = req.headers.authorization || '';
  const provided = header.startsWith('Bearer ') ? header.slice(7) : null;
  if (provided !== token) {
    return res.status(401).json({ error: 'Token không hợp lệ.' });
  }
  next();
}

router.post('/', checkToken, async (req, res) => {
  try {
    const { title, content, link, imageBase64 } = req.body || {};
    if (!title || !content) {
      return res.status(400).json({ error: 'Thiếu title hoặc content.' });
    }

    let coverImageUrl;
    if (imageBase64) {
      const buffer = Buffer.from(imageBase64, 'base64');
      const filename = `${Date.now()}-${crypto.randomBytes(6).toString('hex')}.jpg`;
      fs.writeFileSync(path.join(uploadDir, filename), buffer);
      coverImageUrl = `/uploads/${filename}`;
    }

    const post = await BlogPost.create({
      title,
      content,
      excerpt: String(content).slice(0, 160),
      sourceUrl: link || null,
      isAutoGenerated: true,
      isPublished: true,
      ...(coverImageUrl ? { coverImageUrl } : {}),
    });

    res.json({ ok: true, id: post.id, slug: post.slug, url: `/blog/${post.slug}` });
  } catch (e) {
    console.error('[autopost] error', e);
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
