// Nhận bài đăng từ công cụ bên ngoài (A-AI-3dvietpro desktop tool — mục "AI
// tự động đăng bài" / hàng chờ "Đăng bài tự động") và lưu thành 1 bài blog
// thật trên chính site này, để trang /blog tự động hiện bài mới — không cần
// sửa gì thêm ở phía web, vì trang blog đã đọc thẳng từ bảng BlogPost.
//
// Xác thực bằng 1 Bearer token tĩnh (AUTOPOST_API_TOKEN, đặt trong biến môi
// trường ở cPanel) — đơn giản, đủ dùng cho 1 client duy nhất (tool của thầy),
// không cần OAuth/session vì đây là gọi máy-tới-máy, không có trình duyệt.
const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const BlogPost = require('../models/BlogPost');
const { markdownToHtml } = require('../utils/markdownToHtml');
const { fetchStockImage } = require('../services/newsFactoryService');

const uploadDir = path.join(__dirname, '..', 'public', 'uploads');

function checkToken(req, res, next) {
  const token = process.env.AUTOPOST_API_TOKEN;
  if (!token) {
    return res.status(503).json({ error: 'Server chưa cấu hình AUTOPOST_API_TOKEN.' });
  }
  const header = req.headers.authorization || '';
  const provided = header.startsWith('Bearer ') ? header.slice(7) : null;
  if (provided !== token) {
    return res.status(401).json({ error: 'Token không hợp lệ.' });
  }
  next();
}

router.post('/', checkToken, async (req, res) => {
  try {
    const { title, content, link, imageBase64 } = req.body || {};
    if (!title || !content) {
      return res.status(400).json({ error: 'Thiếu title hoặc content.' });
    }

    let coverImageUrl;
    let coverImageSourceId;
    if (imageBase64) {
      const buffer = Buffer.from(imageBase64, 'base64');
      const filename = `${Date.now()}-${crypto.randomBytes(6).toString('hex')}.jpg`;
      fs.writeFileSync(path.join(uploadDir, filename), buffer);
      coverImageUrl = `/uploads/${filename}`;
    } else {
      // Tool ngoài đôi khi gửi bài không kèm ảnh — thầy yêu cầu rõ PHẢI là
      // ảnh thật, tuyệt đối không dùng icon vẽ minh hoạ (đã thử 1 lần, bị
      // nhắc lại). Dùng đúng pipeline tìm ảnh thật (Wikimedia/Openverse/
      // Pixabay, có Claude xác thực độ liên quan) mà "Nhà máy tin tức AI"
      // đang dùng cho chính nó — không truyền specificQuery vì không có bài
      // viết gốc để sinh từ khoá, fetchStockImage tự rơi về từ khoá chung
      // theo chuyên mục. Nếu không tìm/tải được ảnh thật nào (hiếm), để
      // trống — cột coverImageUrl có default là 1 ảnh JPG thật (không phải
      // SVG vẽ), vẫn đúng yêu cầu "phải là ảnh thật" của thầy.
      const usedImages = await BlogPost.findAll({
        where: { coverImageSourceId: { [require('sequelize').Op.ne]: null } },
        attributes: ['coverImageSourceId'],
      });
      const usedPageIds = new Set(usedImages.map((p) => p.coverImageSourceId));
      const stockImage = await fetchStockImage('ai-cong-nghe', usedPageIds, null, title);
      if (stockImage) {
        coverImageUrl = stockImage.url;
        coverImageSourceId = stockImage.sourceId;
      }
    }

    // content đến từ tool ngoài (A-AI Ads) là text thuần, đoạn cách nhau bằng
    // \n\n — trang blog render thẳng post.content bằng <%- %> (không escape),
    // nên phải bọc thành <p> HTML thật ở đây, nếu không trình duyệt sẽ gộp hết
    // \n thành khoảng trắng và ra 1 khối chữ dính liền (bug thầy báo 16/9/2026).
    const post = await BlogPost.create({
      title,
      content: markdownToHtml(content),
      excerpt: String(content).slice(0, 160),
      sourceUrl: link || null,
      isAutoGenerated: true,
      isPublished: true,
      ...(coverImageUrl ? { coverImageUrl } : {}),
      ...(coverImageSourceId ? { coverImageSourceId } : {}),
    });

    res.json({ ok: true, id: post.id, slug: post.slug, url: `/blog/${post.slug}` });
  } catch (e) {
    console.error('[autopost] error', e);
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
