const { DataTypes } = require('sequelize');
const slugify = require('slugify');
const { sequelize } = require('../config/db');
const HERO_SHOPEE_LINKS = require('../data/heroShopeeLinks');

const HERO_SHOPEE_MARKER = /<!-- hero-shopee:(https:\/\/s\.shopee\.vn\/\S+) -->/;

const BlogPost = sequelize.define(
  'BlogPost',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    _id: { type: DataTypes.VIRTUAL, get() { return this.id; } },
    title: { type: DataTypes.STRING, allowNull: false },
    slug: { type: DataTypes.STRING, unique: true },
    excerpt: { type: DataTypes.STRING, defaultValue: '' },
    content: { type: DataTypes.TEXT, allowNull: false },
    // JPG, not SVG: Facebook's link-scraper can't read SVG dimensions and
    // silently substitutes a wrong/generic image on auto-shared posts.
    coverImageUrl: { type: DataTypes.STRING, defaultValue: '/images/blog/blog-placeholder-photo.jpg' },
    category: { type: DataTypes.STRING, defaultValue: 'ai-cong-nghe', allowNull: false },
    tags: { type: DataTypes.JSON, defaultValue: [] },
    // Bài do "Nhà máy tin tức AI" tự động tổng hợp & đăng (không phải thầy tự viết).
    isAutoGenerated: { type: DataTypes.BOOLEAN, defaultValue: false },
    // Link nguồn RSS gốc đầu tiên dùng để viết bài — dùng để tránh viết trùng
    // 1 tin đã tổng hợp rồi, và để hiển thị "nguồn tham khảo".
    sourceUrl: { type: DataTypes.STRING, allowNull: true },
    // Từ khoá SEO mà bài này nhắm tới — chỉ để theo dõi/báo cáo, không hiển thị.
    seoKeyword: { type: DataTypes.STRING, allowNull: true },
    // pageid của ảnh Wikimedia Commons đang dùng làm coverImageUrl — chỉ để
    // kiểm tra trùng lặp giữa các bài tự động, không hiển thị.
    coverImageSourceId: { type: DataTypes.STRING, allowNull: true },
    commentImages: { type: DataTypes.JSON, defaultValue: [] },
    isPublished: { type: DataTypes.BOOLEAN, defaultValue: true },
    publishedAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    viewCount: { type: DataTypes.INTEGER, defaultValue: 0 },
  },
  {
    tableName: 'blog_posts',
    hooks: {
      beforeValidate: (post) => {
        if (post.title && !post.slug) {
          post.slug = `${slugify(post.title, { lower: true, strict: true })}-${Date.now().toString(36)}`;
        }
      },
      // Thầy muốn MỌI bài đăng trên web (không riêng bài tự động) đều có 1
      // link Shopee gắn vào ảnh bìa để bấm vào là ra thẳng link đó — đặt ở
      // đây (model hook) thay vì ở từng chỗ tạo bài, để không bỏ sót dù bài
      // được tạo qua đường nào (nhà máy tin tức tự động, trang quản trị,
      // API auto-post...). Đánh dấu bằng comment HTML vô hình trong content,
      // blogController đọc lại marker này để build link khi hiển thị bài.
      beforeCreate: (post) => {
        if (post.content && !HERO_SHOPEE_MARKER.test(post.content)) {
          const link = HERO_SHOPEE_LINKS[Math.floor(Math.random() * HERO_SHOPEE_LINKS.length)];
          post.content += `\n<!-- hero-shopee:${link} -->`;
        }
      },
    },
  }
);

module.exports = BlogPost;
